# Permalinks
permalink:           pretty

# Setup
title:               Top 100
tagline:             All my yearly charts in one place
url:                 http://erikjalevik.github.io/top100
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Erik Jälevik

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
